---
- name: "write to a single new file to the target machine"
  hosts: localhost
  tasks:
    - name: "write to a file"
      copy:
        content: "Hello, World... thank you!"
        dest: "/tmp/hello.txt"
